2022-04-28 06:58:20|   DEBUG|testAction.py[:57]|sniper
2022-04-28 06:58:20|   DEBUG|testAction.py[:58]|123
2022-04-28 06:58:20|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-28 06:58:20|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-28 07:01:05|   DEBUG|testAction.py[:57]|admin
2022-04-28 07:01:05|   DEBUG|testAction.py[:58]|123456
2022-04-28 07:01:05|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-28 07:01:05|   DEBUG|testAction.py[:57]|sniper
2022-04-28 07:01:05|   DEBUG|testAction.py[:58]|111111
2022-04-28 07:01:05|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-28 07:01:05|   DEBUG|testAction.py[:57]|sniper
2022-04-28 07:01:05|   DEBUG|testAction.py[:58]|123
2022-04-28 07:01:05|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-28 07:01:05|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-29 06:12:06|   DEBUG|selector_events.py[:59]|Using selector: KqueueSelector
2022-04-29 06:12:14| WARNING|log.py[:224]|Not Found: /
2022-04-29 06:12:14| WARNING|log.py[:224]|Not Found: /favicon.ico
2022-04-29 06:12:18| WARNING|log.py[:224]|Not Found: /index
2022-04-29 06:30:56|   DEBUG|testAction.py[:57]|admin
2022-04-29 06:30:56|   DEBUG|testAction.py[:58]|123456
2022-04-29 06:30:56|   ERROR|testAction.py[:73]|[Errno 32] Broken pipe
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 60, in dologin
    print(user_obj)
BrokenPipeError: [Errno 32] Broken pipe
2022-04-29 06:30:56|    INFO|testAction.py[:78]|response json: {'code': -1, 'msg': '[Errno 32] Broken pipe'}
2022-04-29 06:30:56|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:30:56|   DEBUG|testAction.py[:58]|111111
2022-04-29 06:30:56|   ERROR|testAction.py[:73]|[Errno 32] Broken pipe
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 60, in dologin
    print(user_obj)
BrokenPipeError: [Errno 32] Broken pipe
2022-04-29 06:30:56|    INFO|testAction.py[:78]|response json: {'code': -1, 'msg': '[Errno 32] Broken pipe'}
2022-04-29 06:30:56|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:30:56|   DEBUG|testAction.py[:58]|123
2022-04-29 06:30:56|   ERROR|testAction.py[:73]|[Errno 32] Broken pipe
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 60, in dologin
    print(user_obj)
BrokenPipeError: [Errno 32] Broken pipe
2022-04-29 06:30:56|    INFO|testAction.py[:78]|response json: {'code': -1, 'msg': '[Errno 32] Broken pipe'}
2022-04-29 06:33:48|   DEBUG|selector_events.py[:59]|Using selector: KqueueSelector
2022-04-29 06:35:53| WARNING|log.py[:224]|Not Found: /
2022-04-29 06:36:02|   DEBUG|testAction.py[:57]|admin
2022-04-29 06:36:02|   DEBUG|testAction.py[:58]|123456
2022-04-29 06:36:03|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:36:03|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:36:03|   DEBUG|testAction.py[:58]|111111
2022-04-29 06:36:03|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:36:03|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:36:03|   DEBUG|testAction.py[:58]|123
2022-04-29 06:36:03|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-29 06:36:03|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-29 06:45:35|   DEBUG|testAction.py[:57]|admin
2022-04-29 06:45:35|   DEBUG|testAction.py[:58]|123456
2022-04-29 06:45:35|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:45:35|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:45:35|   DEBUG|testAction.py[:58]|111111
2022-04-29 06:45:35|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:45:35|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:45:35|   DEBUG|testAction.py[:58]|123
2022-04-29 06:45:35|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-29 06:45:35|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-29 06:46:11|   DEBUG|testAction.py[:57]|admin
2022-04-29 06:46:11|   DEBUG|testAction.py[:58]|123456
2022-04-29 06:46:11|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:46:11|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:46:11|   DEBUG|testAction.py[:58]|111111
2022-04-29 06:46:11|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:46:11|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:46:11|   DEBUG|testAction.py[:58]|123
2022-04-29 06:46:11|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-29 06:46:11|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-29 06:47:10|   DEBUG|testAction.py[:57]|admin
2022-04-29 06:47:10|   DEBUG|testAction.py[:58]|123456
2022-04-29 06:47:10|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:47:10|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:47:10|   DEBUG|testAction.py[:58]|111111
2022-04-29 06:47:10|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:47:10|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:47:10|   DEBUG|testAction.py[:58]|123
2022-04-29 06:47:10|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-29 06:47:10|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-29 06:47:26|   DEBUG|testAction.py[:57]|admin
2022-04-29 06:47:26|   DEBUG|testAction.py[:58]|123456
2022-04-29 06:47:26|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:47:26|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:47:26|   DEBUG|testAction.py[:58]|111111
2022-04-29 06:47:26|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:47:26|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:47:26|   DEBUG|testAction.py[:58]|123
2022-04-29 06:47:26|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-29 06:47:26|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-29 06:47:57|   DEBUG|testAction.py[:57]|admin
2022-04-29 06:47:57|   DEBUG|testAction.py[:58]|123456
2022-04-29 06:47:58|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:47:58|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:47:58|   DEBUG|testAction.py[:58]|111111
2022-04-29 06:47:58|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:47:58|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:47:58|   DEBUG|testAction.py[:58]|123
2022-04-29 06:47:58|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-29 06:47:58|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-29 06:51:30|   DEBUG|testAction.py[:57]|admin
2022-04-29 06:51:30|   DEBUG|testAction.py[:58]|123456
2022-04-29 06:51:30|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:51:30|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:51:30|   DEBUG|testAction.py[:58]|111111
2022-04-29 06:51:30|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:51:30|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:51:30|   DEBUG|testAction.py[:58]|123
2022-04-29 06:51:30|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-29 06:51:30|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-29 06:52:39|   DEBUG|testAction.py[:57]|admin
2022-04-29 06:52:39|   DEBUG|testAction.py[:58]|123456
2022-04-29 06:52:39|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:52:39|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:52:39|   DEBUG|testAction.py[:58]|111111
2022-04-29 06:52:39|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:52:39|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:52:39|   DEBUG|testAction.py[:58]|123
2022-04-29 06:52:39|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-29 06:52:39|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-29 06:52:49|   DEBUG|testAction.py[:57]|admin
2022-04-29 06:52:49|   DEBUG|testAction.py[:58]|123456
2022-04-29 06:52:49|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:52:49|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:52:49|   DEBUG|testAction.py[:58]|111111
2022-04-29 06:52:49|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:52:49|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:52:49|   DEBUG|testAction.py[:58]|123
2022-04-29 06:52:49|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-29 06:52:49|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-29 06:52:57|   DEBUG|testAction.py[:57]|admin
2022-04-29 06:52:57|   DEBUG|testAction.py[:58]|123456
2022-04-29 06:52:57|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:52:57|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:52:57|   DEBUG|testAction.py[:58]|111111
2022-04-29 06:52:58|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:52:58|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:52:58|   DEBUG|testAction.py[:58]|123
2022-04-29 06:52:58|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-29 06:52:58|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-29 06:53:24|   DEBUG|testAction.py[:57]|admin
2022-04-29 06:53:24|   DEBUG|testAction.py[:58]|123456
2022-04-29 06:53:24|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:53:24|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:53:24|   DEBUG|testAction.py[:58]|111111
2022-04-29 06:53:24|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:53:24|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:53:24|   DEBUG|testAction.py[:58]|123
2022-04-29 06:53:24|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-29 06:53:24|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-29 06:56:03|   DEBUG|testAction.py[:57]|admin
2022-04-29 06:56:03|   DEBUG|testAction.py[:58]|123456
2022-04-29 06:56:03|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:56:03|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:56:03|   DEBUG|testAction.py[:58]|111111
2022-04-29 06:56:03|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:56:03|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:56:03|   DEBUG|testAction.py[:58]|123
2022-04-29 06:56:03|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-29 06:56:03|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-29 06:56:30|   DEBUG|testAction.py[:57]|admin
2022-04-29 06:56:30|   DEBUG|testAction.py[:58]|123456
2022-04-29 06:56:30|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:56:31|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:56:31|   DEBUG|testAction.py[:58]|111111
2022-04-29 06:56:31|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 06:56:31|   DEBUG|testAction.py[:57]|sniper
2022-04-29 06:56:31|   DEBUG|testAction.py[:58]|123
2022-04-29 06:56:31|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-29 06:56:31|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-29 07:00:12|   DEBUG|testAction.py[:57]|admin
2022-04-29 07:00:12|   DEBUG|testAction.py[:58]|123456
2022-04-29 07:00:13|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 07:00:13|   DEBUG|testAction.py[:57]|sniper
2022-04-29 07:00:13|   DEBUG|testAction.py[:58]|111111
2022-04-29 07:00:13|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 07:00:13|   DEBUG|testAction.py[:57]|sniper
2022-04-29 07:00:13|   DEBUG|testAction.py[:58]|123
2022-04-29 07:00:13|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-29 07:00:13|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-29 07:01:13|   DEBUG|testAction.py[:57]|admin
2022-04-29 07:01:13|   DEBUG|testAction.py[:58]|123456
2022-04-29 07:01:13|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 07:01:13|   DEBUG|testAction.py[:57]|sniper
2022-04-29 07:01:13|   DEBUG|testAction.py[:58]|111111
2022-04-29 07:01:13|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 07:01:13|   DEBUG|testAction.py[:57]|sniper
2022-04-29 07:01:13|   DEBUG|testAction.py[:58]|123
2022-04-29 07:01:13|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-29 07:01:13|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-29 07:01:46|   DEBUG|testAction.py[:57]|admin
2022-04-29 07:01:46|   DEBUG|testAction.py[:58]|123456
2022-04-29 07:01:46|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 07:01:46|   DEBUG|testAction.py[:57]|sniper
2022-04-29 07:01:46|   DEBUG|testAction.py[:58]|111111
2022-04-29 07:01:46|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 07:01:46|   DEBUG|testAction.py[:57]|sniper
2022-04-29 07:01:46|   DEBUG|testAction.py[:58]|123
2022-04-29 07:01:46|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-29 07:01:46|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-29 07:06:29|   DEBUG|testAction.py[:57]|admin
2022-04-29 07:06:29|   DEBUG|testAction.py[:58]|123456
2022-04-29 07:06:29|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 07:06:29|   DEBUG|testAction.py[:57]|sniper
2022-04-29 07:06:29|   DEBUG|testAction.py[:58]|111111
2022-04-29 07:06:30|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 07:06:30|   DEBUG|testAction.py[:57]|sniper
2022-04-29 07:06:30|   DEBUG|testAction.py[:58]|123
2022-04-29 07:06:30|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-29 07:06:30|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-29 07:09:55|   DEBUG|testAction.py[:57]|admin
2022-04-29 07:09:55|   DEBUG|testAction.py[:58]|123456
2022-04-29 07:09:55|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 07:09:55|   DEBUG|testAction.py[:57]|sniper
2022-04-29 07:09:55|   DEBUG|testAction.py[:58]|111111
2022-04-29 07:09:55|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 07:09:55|   DEBUG|testAction.py[:57]|sniper
2022-04-29 07:09:55|   DEBUG|testAction.py[:58]|123
2022-04-29 07:09:55|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
2022-04-29 07:09:55|    INFO|testAction.py[:78]|response json: {'code': 11, 'msg': '用户名或密码错误'}
2022-04-29 07:10:46|   DEBUG|testAction.py[:57]|admin
2022-04-29 07:10:46|   DEBUG|testAction.py[:58]|123456
2022-04-29 07:10:46|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 07:10:46|   DEBUG|testAction.py[:57]|sniper
2022-04-29 07:10:46|   DEBUG|testAction.py[:58]|111111
2022-04-29 07:10:46|    INFO|testAction.py[:78]|response json: {'code': 0}
2022-04-29 07:10:46|   DEBUG|testAction.py[:57]|sniper
2022-04-29 07:10:46|   DEBUG|testAction.py[:58]|123
2022-04-29 07:10:46|   ERROR|testAction.py[:73]|用户名或密码错误
Traceback (most recent call last):
  File "/Users/ziqguo/Documents/testdev/testProject/testProject/testAction.py", line 67, in dologin
    raise RuntimeError("用户名或密码错误")
RuntimeError: 用户名或密码错误
